### ISSUE TITLE
D3D12 headless_compute benchmark fails on storage buffer creation

### ISSUE THREAD

**Issue by amaiorano** [google/bigwheels#6] opened 2022-11-11 14:08 UTC
I am trying to run the headless_compute benchmark, but it fails when creating the storage buffer:

```
     RaiseException()    Unknown
     _CxxThrowException()    Unknown
     CDevice::CreatePlacedResource_Worker(struct ID3D12Heap *,unsigned __int64,struct D3D12_RESOURCE_DESC1 const *,enum D3D12_RESOURCE_STATES,struct D3D12_CLEAR_VALUE const *,struct _GUID const &,void * *)    Unknown
     CDevice::CreatePlacedResource(struct ID3D12Heap *,unsigned __int64,struct D3D12_RESOURCE_DESC const *,enum D3D12_RESOURCE_STATES,struct D3D12_CLEAR_VALUE const *,struct _GUID const &,void * *)    Unknown
>    D3D12MA::BlockVector::CreateResource(unsigned __int64 size, unsigned __int64 alignment, const D3D12MA::ALLOCATION_DESC & allocDesc, const D3D12_RESOURCE_DESC & resourceDesc, D3D12_RESOURCE_STATES InitialResourceState, const D3D12_CLEAR_VALUE * pOptimizedClearValue, D3D12MA::Allocation * * ppAllocation, const _GUID & riidResource, void * * ppvResource) Line 8484    C++
     D3D12MA::AllocatorPimpl::CreateResource(const D3D12MA::ALLOCATION_DESC * pAllocDesc, const D3D12_RESOURCE_DESC * pResourceDesc, D3D12_RESOURCE_STATES InitialResourceState, const D3D12_CLEAR_VALUE * pOptimizedClearValue, D3D12MA::Allocation * * ppAllocation, const _GUID & riidResource, void * * ppvResource) Line 6840    C++
     D3D12MA::Allocator::CreateResource(const D3D12MA::ALLOCATION_DESC * pAllocDesc, const D3D12_RESOURCE_DESC * pResourceDesc, D3D12_RESOURCE_STATES InitialResourceState, const D3D12_CLEAR_VALUE * pOptimizedClearValue, D3D12MA::Allocation * * ppAllocation, const _GUID & riidResource, void * * ppvResource) Line 10024    C++
     ppx::grfx::dx12::Buffer::CreateApiObjects(const ppx::grfx::BufferCreateInfo * pCreateInfo) Line 64    C++
     ppx::grfx::CreateDestroyTraits<ppx::grfx::BufferCreateInfo>::Create(const ppx::grfx::BufferCreateInfo * pCreateInfo) Line 236    C++
     ppx::grfx::Buffer::Create(const ppx::grfx::BufferCreateInfo * pCreateInfo) Line 35    C++
     ppx::grfx::Device::CreateObject<ppx::grfx::Buffer,ppx::grfx::BufferCreateInfo,std::vector<ObjPtr<ppx::grfx::Buffer>,std::allocator<ObjPtr<ppx::grfx::Buffer>>>>(const ppx::grfx::BufferCreateInfo * pCreateInfo, std::vector<ObjPtr<ppx::grfx::Buffer>,std::allocator<ObjPtr<ppx::grfx::Buffer>>> & container, ppx::grfx::Buffer * * ppObject) Line 110    C++
     ppx::grfx::Device::CreateBuffer(const ppx::grfx::BufferCreateInfo * pCreateInfo, ppx::grfx::Buffer * * ppBuffer) Line 233    C++
     ProjApp::SetupComputeShaderPass() Line 164    C++
     ProjApp::Setup() Line 138    C++
     ppx::Application::DispatchSetup() Line 1003    C++
     ppx::Application::Run(int argc, char * * argv) Line 1365    C++
     main(int argc, char * * argv) Line 281    C++
```

The call to `hr = m_hAllocator->GetDevice()->CreatePlacedResource` is failing with `E_INVALIDARG One or more arguments are invalid.`.

**Comment by vettoreldaniele** [comment] 2022-11-11 15:54
Duplicate of #5

**Closed by vettoreldaniele** 2022-11-11 15:54 UTC
Labels: bug
